global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: quickstart-aws-vpc
  regions:
    - us-east-1

  reporting: true
tests:
  defaults:
    parameter_input: aws-vpc-defaults.json
    template_file: aws-vpc.template
  complete:
    parameter_input: aws-vpc-complete.json
    template_file: aws-vpc.template
  public:
    parameter_input: aws-vpc-public.json
    template_file: aws-vpc.template